interface=ovs_bond0
bind-dynamic
# enable-tftp
# tftp-root=/shared/tftpboot
# tftp-unique-root=mac
# log-queries

# Configure listening for DNS (0 disables DNS)
port=53

log-dhcp
dhcp-range=10.0.0.1,proxy,255.255.0.0

pxe-service=0,"Raspberry Pi Boot"
dhcp-match=set:aarch64,60,PXEClient:Arch:00011:UNDI:003000

dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe
pxe-service=tag:ipxe,x86PC,"iPXE",https://ironic.appkins.io/boot.ipxe
pxe-service=tag:#ipxe,ARM32_EFI,"PXE chainload to iPXE UEFI 32",snp-arm64.efi
pxe-service=tag:ipxe,ARM32_EFI,"iPXE UEFI 32",https://ironic.appkins.io/boot.ipxe
pxe-service=tag:#ipxe,ARM64_EFI,"PXE chainload to iPXE UEFI",snp-arm64.efi
pxe-service=tag:ipxe,ARM64_EFI,"iPXE UEFI",https://ironic.appkins.io/boot.ipxe
pxe-service=tag:#ipxe,X86-64_EFI,"PXE chainload to iPXE UEFI",snp-x86_64.efi
pxe-service=tag:ipxe,X86-64_EFI,"iPXE UEFI",https://ironic.appkins.io/boot.ipxe
dhcp-boot=tag:ipxe,https://ironic.appkins.io/boot.ipxe

dhcp-match=ipxe,175
dhcp-boot=tag:ipxe,https://ironic.appkins.io/boot.ipxe


# Note: Need to test EFI booting
dhcp-match=set:efi,option:client-arch,7
dhcp-match=set:efi,option:client-arch,9
dhcp-match=set:efi,option:client-arch,11
dhcp-boot=tag:efi,tag:!ipxe,snponly.efi

# Client is running PXE over BIOS; send BIOS version of iPXE chainloader
dhcp-boot=/undionly.kpxe,10.0.50.1
# IPv6 Configuration:
# enable-ra
# ra-param=ovs_bond0,0,0

dhcp-vendorclass=set:pxe6,enterprise:343,PXEClient
dhcp-userclass=set:ipxe6,iPXE
dhcp-option=tag:pxe6,option6:bootfile-url,snponly.efi
dhcp-option=tag:ipxe6,option6:bootfile-url,https://ironic.appkins.io/boot.ipxe

dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
