[DEFAULT]
auth_strategy = noauth
debug = true
enable_new_agents = true
bind_port = 3232
transport_url = "fake://"
api_workers = 1
allow_overlapping_ips = true
state_path = "/var/lib/neutron"
core_plugin = "ml2"
# service_plugins = "router"
allow_automatic_l3agent_failover = true
network_auto_schedule = true
router_auto_schedule  = true
interface_driver      = noop

[oslo_concurrency]
lock_path = "/var/lib/neutron/tmp"

[oslo_messaging_notifications]
driver = log
transport_url = fake://

[database]
max_retries = -1
engine = "sqlite"
connection = "sqlite:////var/lib/neutron/neutron.sqlite"

[ironic]
auth_type = "noauth"
